packages:
  - packages/*
  - docs
  - packages/playground/**
  - packages/react-devtools-plugins/**

catalog:
  '@iconify/json': ^2.2.395
  '@types/node': ^24.7.2
  '@types/react': ^18.2.72
  '@types/react-dom': ^18.2.23
  '@unocss/reset': ^66.5.4
  '@vitejs/plugin-react': ^4.3.2
  birpc: ^0.2.19
  colord: ^2.9.3
  mitt: ^3.0.1
  pathe: ^2.0.3
  perfect-debounce: ^2.0.0
  react: ^18.3.1
  react-dom: ^18.3.1
  sass-embedded: ^1.93.2
  serve: ^14.2.5
  shiki: ^3.13.0
  tsdown: ^0.15.7
  tsup: ^8.5.1
  typescript: ^5.9.3
  unocss: ^66.5.4
  unplugin-auto-import: ^20.2.0
  vite: ^7.1.10
  vite-hot-client: ^2.1.0
  vite-plugin-dts: ^4.5.4
  vite-plugin-inspect: ^11.3.3
