import { copyFileSync, cpSync, existsSync, rmSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { defineConfig } from 'tsup'

const __dirname = dirname(fileURLToPath(import.meta.url))

/**
 * ESM __dirname polyfill banner
 * This banner injects a safe __dirname polyfill for ESM modules
 * It handles case where import.meta.url might be undefined (e.g., in some bundler scenarios)
 */
const esmDirnameBanner = `
import { dirname as __pathDirname } from 'path';
import { fileURLToPath as __fileURLToPath } from 'url';
var __dirname = (function() {
  try {
    var url = import.meta?.url;
    if (url) return __pathDirname(__fileURLToPath(url));
  } catch (e) {}
  try {
    if (typeof __filename !== 'undefined') return __pathDirname(__filename);
  } catch (e) {}
  return process.cwd();
})();
`.trim()

// Common config for plugin entries
const commonConfig = {
  target: 'es2017',
  outDir: 'dist',
  splitting: false,
  sourcemap: true,
  external: [
    'vite',
    'webpack',
    'react',
    'react-dom',
  ],
  skipNodeModulesBundle: true,
}

// Common config for main plugin entry
const mainEntryCommon = {
  entry: ['src/index.ts'],
  dts: true,
  ...commonConfig,
}

// Common config for vite entry
const viteEntryCommon = {
  entry: { vite: 'src/vite.ts' },
  dts: true,
  ...commonConfig,
}

// Common config for webpack entry
const webpackEntryCommon = {
  entry: { webpack: 'src/webpack.ts' },
  dts: true,
  ...commonConfig,
}

// Common config for umi entry
const umiEntryCommon = {
  entry: { umi: 'src/umi.ts' },
  dts: true,
  ...commonConfig,
}

export default defineConfig([
  // Main plugin entry - ESM with __dirname polyfill
  {
    ...mainEntryCommon,
    format: ['esm'],
    shims: false,
    clean: true,
    banner: {
      js: esmDirnameBanner,
    },
  },
  // Main plugin entry - CJS (native __dirname)
  {
    ...mainEntryCommon,
    format: ['cjs'],
    shims: false,
    clean: false,
    dts: false, // DTS already generated by ESM build
  },
  // Vite entry - ESM with __dirname polyfill
  {
    ...viteEntryCommon,
    format: ['esm'],
    shims: false,
    clean: false,
    banner: {
      js: esmDirnameBanner,
    },
  },
  // Vite entry - CJS (native __dirname)
  {
    ...viteEntryCommon,
    format: ['cjs'],
    shims: false,
    clean: false,
    dts: false,
  },
  // Webpack entry - ESM with __dirname polyfill
  {
    ...webpackEntryCommon,
    format: ['esm'],
    shims: false,
    clean: false,
    banner: {
      js: esmDirnameBanner,
    },
  },
  // Webpack entry - CJS (native __dirname)
  {
    ...webpackEntryCommon,
    format: ['cjs'],
    shims: false,
    clean: false,
    dts: false,
  },
  // Umi entry - ESM with __dirname polyfill
  {
    ...umiEntryCommon,
    format: ['esm'],
    shims: false,
    clean: false,
    banner: {
      js: esmDirnameBanner,
    },
  },
  // Umi entry - CJS (native __dirname)
  {
    ...umiEntryCommon,
    format: ['cjs'],
    shims: false,
    clean: false,
    dts: false,
  },
  // Scan entry - bundle @react-devtools-plus/scan without resolving its types
  {
    entry: ['src/scan.ts'],
    format: ['esm', 'cjs'],
    target: 'es2017',
    dts: false,
    outDir: 'dist',
    shims: false,
    clean: false,
    splitting: false,
    sourcemap: true,
    external: [
      'react',
      'react-dom',
    ],
    noExternal: [
      '@react-devtools-plus/scan',
    ],
    skipNodeModulesBundle: false,
    onSuccess: async () => {
      // Copy type declarations from @react-devtools-plus/scan
      const scanDtsPath = resolve(__dirname, '../react-devtools-scan/dist/index.d.ts')
      const scanDctPath = resolve(__dirname, '../react-devtools-scan/dist/index.cts')
      const targetDtsPath = resolve(__dirname, 'dist/scan.d.ts')
      const targetDctPath = resolve(__dirname, 'dist/scan.cts')

      if (existsSync(scanDtsPath)) {
        copyFileSync(scanDtsPath, targetDtsPath)
      }
      if (existsSync(scanDctPath)) {
        copyFileSync(scanDctPath, targetDctPath)
      }

      // Copy react-devtools-client/dist to client/ directory
      // This ensures the DevTools client UI is included in the package
      const clientSourcePath = resolve(__dirname, '../react-devtools-client/dist')
      const clientTargetPath = resolve(__dirname, 'client')

      if (existsSync(clientSourcePath)) {
        // Remove old client directory contents (except keep directory)
        if (existsSync(clientTargetPath)) {
          rmSync(clientTargetPath, { recursive: true, force: true })
        }
        // Copy new client files
        cpSync(clientSourcePath, clientTargetPath, { recursive: true })
      }
      else {
        console.warn('Warning: react-devtools-client/dist not found, client UI will not be available')
      }
    },
  },
])
